/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookstoreinventorymanagementsystem;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Liew Wen Yen
 */
public class ManageSales extends javax.swing.JFrame {

    private final SalesData salesData;
    private final UserData userData;
    private String salesID;
    private double totalPrice;
    private String salesDate;

    /**
     * Creates new form ManageInvoice
     *
     * @param salesData
     * @param userData
     */
    public ManageSales(SalesData salesData, UserData userData) {
        initComponents();
        setLocationRelativeTo(null);
        this.salesData = salesData;
        this.userData = userData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        lblBlueStrip = new javax.swing.JPanel();
        homeButton = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        HomePage = new javax.swing.JLabel();
        lblGreenStrip = new javax.swing.JPanel();
        TotalLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        salesIDLabel = new javax.swing.JLabel();
        TotalLabel3 = new javax.swing.JLabel();
        TotalLabel4 = new javax.swing.JLabel();
        salesDateLabel = new javax.swing.JLabel();
        TotalLabel8 = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        generateBillButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book Name", "Quantity", "Price (RM)", "Sub Total (RM)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(salesTable);
        if (salesTable.getColumnModel().getColumnCount() > 0) {
            salesTable.getColumnModel().getColumn(0).setResizable(false);
            salesTable.getColumnModel().getColumn(1).setResizable(false);
            salesTable.getColumnModel().getColumn(2).setResizable(false);
            salesTable.getColumnModel().getColumn(3).setResizable(false);
        }

        lblBlueStrip.setBackground(new java.awt.Color(0, 140, 214));
        lblBlueStrip.setForeground(new java.awt.Color(51, 102, 255));
        lblBlueStrip.setPreferredSize(new java.awt.Dimension(45, 28));

        homeButton.setBackground(new java.awt.Color(0, 140, 214));
        homeButton.setPreferredSize(new java.awt.Dimension(136, 33));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                homeButtonMouseReleased(evt);
            }
        });

        homeIcon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homeIcon.setForeground(new java.awt.Color(255, 255, 255));
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Home Icon.png"))); // NOI18N
        homeIcon.setPreferredSize(new java.awt.Dimension(33, 30));

        javax.swing.GroupLayout homeButtonLayout = new javax.swing.GroupLayout(homeButton);
        homeButton.setLayout(homeButtonLayout);
        homeButtonLayout.setHorizontalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeButtonLayout.setVerticalGroup(
            homeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout lblBlueStripLayout = new javax.swing.GroupLayout(lblBlueStrip);
        lblBlueStrip.setLayout(lblBlueStripLayout);
        lblBlueStripLayout.setHorizontalGroup(
            lblBlueStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        lblBlueStripLayout.setVerticalGroup(
            lblBlueStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        HomePage.setBackground(new java.awt.Color(0, 140, 214));
        HomePage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        HomePage.setForeground(new java.awt.Color(0, 140, 214));
        HomePage.setText("Sales");

        lblGreenStrip.setBackground(new java.awt.Color(62, 164, 52));

        javax.swing.GroupLayout lblGreenStripLayout = new javax.swing.GroupLayout(lblGreenStrip);
        lblGreenStrip.setLayout(lblGreenStripLayout);
        lblGreenStripLayout.setHorizontalGroup(
            lblGreenStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lblGreenStripLayout.setVerticalGroup(
            lblGreenStripLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        TotalLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TotalLabel.setForeground(new java.awt.Color(0, 100, 0));
        TotalLabel.setText("Bill To: ");

        customerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        customerNameLabel.setForeground(new java.awt.Color(0, 100, 0));
        customerNameLabel.setText("Customer Name");

        salesIDLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        salesIDLabel.setForeground(new java.awt.Color(0, 100, 0));
        salesIDLabel.setText("salesID");

        TotalLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TotalLabel3.setForeground(new java.awt.Color(0, 100, 0));
        TotalLabel3.setText("Sales ID:");

        TotalLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TotalLabel4.setForeground(new java.awt.Color(0, 100, 0));
        TotalLabel4.setText("Sales Date:");

        salesDateLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        salesDateLabel.setForeground(new java.awt.Color(0, 100, 0));
        salesDateLabel.setText("salesDate");

        TotalLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        TotalLabel8.setForeground(new java.awt.Color(0, 100, 0));
        TotalLabel8.setText("Total: RM");

        totalPriceLabel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        totalPriceLabel.setForeground(new java.awt.Color(0, 100, 0));
        totalPriceLabel.setText("00.0");

        generateBillButton.setBackground(new java.awt.Color(0, 140, 214));
        generateBillButton.setPreferredSize(new java.awt.Dimension(136, 33));
        generateBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateBillButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generateBillButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generateBillButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                generateBillButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                generateBillButtonMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Generate Bill");

        javax.swing.GroupLayout generateBillButtonLayout = new javax.swing.GroupLayout(generateBillButton);
        generateBillButton.setLayout(generateBillButtonLayout);
        generateBillButtonLayout.setHorizontalGroup(
            generateBillButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generateBillButtonLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        generateBillButtonLayout.setVerticalGroup(
            generateBillButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGreenStrip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblBlueStrip, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(HomePage)
                .addGap(408, 408, 408))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TotalLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(totalPriceLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(TotalLabel)
                            .addGap(28, 28, 28)
                            .addComponent(customerNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TotalLabel4)
                                .addComponent(TotalLabel3))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(salesIDLabel)
                                .addComponent(salesDateLabel)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(generateBillButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblBlueStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGreenStrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TotalLabel)
                        .addComponent(customerNameLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salesIDLabel)
                            .addComponent(TotalLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(salesDateLabel)
                            .addComponent(TotalLabel4))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalLabel8)
                    .addComponent(totalPriceLabel))
                .addGap(43, 43, 43)
                .addComponent(generateBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try (Connection con = DatabaseManager.getConnection()) {
            String query = "SELECT p.product_name, sb.quantity, sb.subtotal, p.unit_price, "
                    + "sd.sales_id, sd.sales_date, sd.total_price, "
                    + "c.customer_id, c.name " // Selecting columns from customer and sales_detail tables
                    + "FROM sales_book sb "
                    + "JOIN product p ON sb.product_id = p.product_id "
                    + "JOIN sales_detail sd ON sb.sales_id = sd.sales_id " // Join with sales_detail table
                    + "JOIN customer c ON sd.customer_id = c.customer_id " // Join with customer table
                    + "WHERE sb.sales_id = ?";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, salesData.getCurrentSalesID());
            ResultSet rs = ps.executeQuery();

            DefaultTableModel model = (DefaultTableModel) salesTable.getModel();

            while (rs.next()) {
                String productName = rs.getString("product_name"); // corrected to product_name
                int quantity = rs.getInt("quantity");
                double unitPrice = rs.getDouble("unit_price");
                double subtotal = rs.getDouble("subtotal");

                model.addRow(new Object[]{productName, quantity, unitPrice, subtotal});

                // Set values to labels
                customerNameLabel.setText(rs.getString("name"));
                salesIDLabel.setText(rs.getString("sales_id"));
                salesDateLabel.setText(rs.getString("sales_date"));
                totalPriceLabel.setText(String.valueOf(rs.getDouble("total_price")));
                salesID = rs.getString("sales_id");
                totalPrice = rs.getDouble("total_price");
                salesDate = rs.getString("sales_date");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formComponentShown

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        setVisible(false);
        new SalespersonHomePage().setVisible(true);
    }//GEN-LAST:event_homeButtonMouseClicked

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        homeButton.setBackground(ColorManager.MEDIUM_BLUE);
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        homeButton.setBackground(ColorManager.PRIMARY_BLUE);
    }//GEN-LAST:event_homeButtonMouseExited

    private void homeButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMousePressed
        homeButton.setBackground(ColorManager.DEEP_BLUE);
    }//GEN-LAST:event_homeButtonMousePressed

    private void homeButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseReleased
        homeButton.setBackground(ColorManager.MEDIUM_BLUE);
    }//GEN-LAST:event_homeButtonMouseReleased

    private void generateBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBillButtonMouseClicked
        salesData.setTotalPrice(totalPrice);
        salesData.setSalesID(salesID);
        salesData.setOrderDate(salesDate);

        try {
            salesData.generateBill();
        } catch (DocumentException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(ManageSales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(ManageSales.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(ManageSales.class.getName()).log(Level.SEVERE, null, ex);
        }

        setVisible(false);
        new SalespersonHomePage().setVisible(true);
    }//GEN-LAST:event_generateBillButtonMouseClicked

    private void generateBillButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBillButtonMouseEntered
        generateBillButton.setBackground(ColorManager.MEDIUM_BLUE);
    }//GEN-LAST:event_generateBillButtonMouseEntered

    private void generateBillButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBillButtonMouseExited
        generateBillButton.setBackground(ColorManager.PRIMARY_BLUE);
    }//GEN-LAST:event_generateBillButtonMouseExited

    private void generateBillButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBillButtonMousePressed
        generateBillButton.setBackground(ColorManager.DEEP_BLUE);
    }//GEN-LAST:event_generateBillButtonMousePressed

    private void generateBillButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateBillButtonMouseReleased
        generateBillButton.setBackground(ColorManager.MEDIUM_BLUE);
    }//GEN-LAST:event_generateBillButtonMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSales(new SalesData(new UserData()), new UserData()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomePage;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TotalLabel3;
    private javax.swing.JLabel TotalLabel4;
    private javax.swing.JLabel TotalLabel8;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JPanel generateBillButton;
    private javax.swing.JPanel homeButton;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel lblBlueStrip;
    private javax.swing.JPanel lblGreenStrip;
    private javax.swing.JLabel salesDateLabel;
    private javax.swing.JLabel salesIDLabel;
    private javax.swing.JTable salesTable;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
